var pesos = [
     ['ADMINISTRAÇÃO - BACHARELADO','2','1','1','1','1'],
     ['AGRONOMIA - BACHARELADO','2','2','1','1','2'],
     ['ARQUITETURA E URBANISMO - BACHARELADO','2','1','1','1','1'],
     ['ARTES VISUAIS - BACHARELADO','2','1','2','2','1'],
     ['ARTES VISUAIS - LICENCIATURA','2','1','2','2','1'],
     ['AUDIOVISUAL - BACHARELADO','2','1','1','1','1'],
     ['CIÊNCIA DA COMPUTAÇÃO - BACHARELADO','2','3','2','1','2'],
     ['CIÊNCIAS BIOLÓGICAS - BACHARELADO','2','1','1','1','2'],
     ['CIÊNCIAS BIOLÓGICAS - LICENCIATURA','2','1','1','1','2'],
     ['CIÊNCIAS CONTÁBEIS - BACHARELADO','2','3','1','2','1'],
     ['CIÊNCIAS ECONÔMICAS - BACHARELADO','2','3','1','2','1'],
     ['DIREITO - BACHARELADO','2','2','2','2','1'],
     ['EDUCAÇÃO FÍSICA - BACHARELADO','2','1','2','2','1'],
     ['EDUCAÇÃO FÍSICA - LICENCIATURA','2','1','2','2','1'],
     ['ENFERMAGEM - BACHARELADO','2','1','1','1','2'],
     ['ENGENHARIA CIVIL - BACHARELADO','2','3','1','1','2'],
     ['ENGENHARIA DE COMPUTAÇÃO - BACHARELADO','2','3','1','1','2'],
     ['ENGENHARIA DE PRODUÇÃO - BACHARELADO','2','3','1','1','2'],
     ['ENGENHARIA DE SOFTWARE - BACHARELADO','2','3','2','1','2'],
     ['ENGENHARIA ELÉTRICA - BACHARELADO','2','4','2','1','2'],
     ['ENGENHARIA QUÍMICA - BACHARELADO','2','2','1','1','2'],
     ['FARMÁCIA -  BACHARELADO','2','2','1','1','2'],
     ['FISIOTERAPIA - BACHARELADO','2','1','1','2','2'],
     ['HISTÓRIA - LICENCIATURA','2','1','2','2','1'],
     ['INTERCULTURAL INDÍGENA - LICENCIATURA','2','1','1','1','1'],
     ['JORNALISMO - BACHARELADO','2','1','2','2','1'],
     ['LETRAS - PORTUGUÊS/INGLÊS - LICENCIATURA','2','1','2','1','1'],
     ['MEDICINA - BACHARELADO','2','1','2','2','3'],
     ['MEDICINA VETERINÁRIA - BACHARELADO','2','1','1','1','3'],
     ['MÚSICA - LICENCIATURA','2','1','1','1','1'],
     ['NUTRIÇÃO - BACHARELADO','2','1','1','2','3'],
     ['ODONTOLOGIA - BACHARELADO','2','1','2','2','3'],
     ['PEDAGOGIA - LICENCIATURA','2','1','2','2','1'],
     ['PSICOLOGIA - BACHARELADO','2','1','1','2','1'],
     ['SISTEMAS DE INFORMAÇÃO - BACHARELADO','2','2','2','1','1'],
     ['ZOOTECNIA - BACHARELADO','2','1','1','1','3'],
     ['LICENCIATURA INTERCULTURAL  INDÍGENA - Integral(M,V)','1','1','1','1','1'],
     ['EDUCAÇÃO DO CAMPO - LICENCIATURA - Integral','1','1','1','1','1']
]